import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Page, PrimaryButton, colors } from '../../components/ui';
import { useSession } from '../../context/session';

function Setting({ title, text, value, onChange }: { title: string; text: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.setting}><View style={styles.copy}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingText}>{text}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: '#D9D4E7', true: colors.violet }}/></View>; }
export default function Privacy() { const { dna, privacy, persistSettings, role } = useSession(); const [alerts, setAlerts] = useState(privacy.planAlerts); const [location, setLocation] = useState(privacy.approximateLocation); return <Page title="Приватность и доступы" subtitle="Вы решаете, кто и что может видеть."><View style={styles.info}><Text style={styles.settingTitle}>Кто может отправлять Whisper?</Text><Text style={styles.settingText}>{privacy.whispers === 'friends' ? 'Только друзья' : 'Только подтверждённые пользователи'}</Text><Pressable onPress={() => Alert.alert('Whisper', 'Это лёгкое приглашение. Его можно ограничить или выключить в настройках.')}><Text style={styles.link}>Зачем это нужно?</Text></Pressable></View><Setting title="Уведомления о планах" text="Напомним о согласованиях и событиях" value={alerts} onChange={setAlerts}/><Setting title="Приблизительная геолокация" text="Другим виден район, но не точная точка" value={location} onChange={setLocation}/><Text style={styles.note}>Точные координаты никогда не показываются публично.</Text><PrimaryButton label="Завершить" onPress={() => { persistSettings(dna, { ...privacy, planAlerts: alerts, approximateLocation: location }).then(() => router.replace(role === 'organizer' ? '/(organizer)/home' : '/(user)/home')).catch(() => Alert.alert('Не удалось сохранить', 'Проверьте соединение и попробуйте ещё раз.')); }}/></Page>; }
const styles = StyleSheet.create({ info: { backgroundColor: colors.white, borderColor: colors.border, borderRadius: 20, borderWidth: 1, padding: 18 }, setting: { alignItems: 'center', backgroundColor: colors.white, borderColor: colors.border, borderRadius: 20, borderWidth: 1, flexDirection: 'row', gap: 12, justifyContent: 'space-between', padding: 18 }, copy: { flex: 1 }, settingTitle: { color: colors.text, fontSize: 16, fontWeight: '800' }, settingText: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 4 }, link: { color: colors.violet, fontSize: 14, fontWeight: '800', marginTop: 10 }, note: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: 'center' } });
